export const cities = [
  { value: 'bucuresti', label: 'București' },
  { value: 'cluj-napoca', label: 'Cluj-Napoca' },
  { value: 'timisoara', label: 'Timișoara' },
  { value: 'iasi', label: 'Iași' },
  { value: 'constanta', label: 'Constanța' },
  { value: 'craiova', label: 'Craiova' },
  { value: 'brasov', label: 'Brașov' },
  { value: 'galati', label: 'Galați' },
  { value: 'ploiesti', label: 'Ploiești' },
  { value: 'oradea', label: 'Oradea' },
  { value: 'braila', label: 'Brăila' },
  { value: 'arad', label: 'Arad' },
  { value: 'pitesti', label: 'Pitești' },
  { value: 'sibiu', label: 'Sibiu' },
  { value: 'bacau', label: 'Bacău' },
  { value: 'targu-mures', label: 'Târgu Mureș' },
  { value: 'baia-mare', label: 'Baia Mare' },
  { value: 'buzau', label: 'Buzău' },
  { value: 'botosani', label: 'Botoșani' },
  { value: 'satu-mare', label: 'Satu Mare' },
];
